#ifndef _GMINSTRUMENTTABLE_H_
#define _GMINSTRUMENTTABLE_H_

// GM bank-0 program -> canonical taxonomy path, and the bare-root ->
// preferred-child default redirect table, both mechanically generated from
// docs/instrument-paths.md (the canonical source - see its own "Bank 0" and
// "Defaults for general requests" sections). Regenerate rather than hand-edit
// if that doc changes: the two must stay in sync, and hand-editing either
// table independently is exactly how they'd drift.
//
// Kept as plain data, not behavior - InstrumentProvider::loadSoundFont()
// walks kGmBank0Table to call SoundFont::createInstrumentByProgram()+
// registerPath() once per row; InstrumentProvider::resolvePath()'s
// default-table pass walks kGmPathDefaults. Neither table is SF2-specific in
// shape (just {int, path} and {path, path} pairs) even though only the SF2
// loader populates the first one today - a future non-GM-mapped font would
// register its own paths directly via registerPath(), bypassing this table
// entirely, per docs/instrument-paths.md's own forward-compatibility notes.

struct GmProgramEntry { int program; const char * path; };
struct GmDefaultEntry { const char * request; const char * target; };

// Generated from docs/instrument-paths.md's bank-0 table - do not hand-edit without
// re-deriving from the doc, they must stay in sync.
static constexpr GmProgramEntry kGmBank0Table[] = {
  {0, "piano.acoustic.grand"},
  {1, "piano.acoustic.grand.bright"},
  {2, "piano.electric.grand"},
  {3, "piano.acoustic.upright.honkyTonk"},
  {4, "piano.electric.tine"},
  {5, "piano.electric.fm"},
  {6, "keyboard.plucked.harpsichord"},
  {7, "keyboard.electric.clavinet"},
  {8, "percussion.pitched.metal.celesta"},
  {9, "percussion.pitched.metal.glockenspiel"},
  {10, "percussion.pitched.metal.musicBox"},
  {11, "percussion.pitched.metal.vibraphone"},
  {12, "percussion.pitched.wood.marimba"},
  {13, "percussion.pitched.wood.xylophone"},
  {14, "percussion.pitched.metal.tubularBells"},
  {15, "string.struck.dulcimer"},
  {16, "organ.tonewheel"},
  {17, "organ.tonewheel.percussive"},
  {18, "organ.tonewheel.overdriven"},
  {19, "organ.pipe"},
  {20, "organ.reed"},
  {21, "reed.free.accordion"},
  {22, "reed.free.harmonica"},
  {23, "reed.free.accordion.bandoneon"},
  {24, "guitar.acoustic.nylon"},
  {25, "guitar.acoustic.steel"},
  {26, "guitar.electric.hollow"},
  {27, "guitar.electric.clean"},
  {28, "guitar.electric.muted"},
  {29, "guitar.electric.overdriven"},
  {30, "guitar.electric.distorted"},
  {31, "guitar.electric.harmonics"},
  {32, "bass.acoustic.upright"},
  {33, "bass.electric.finger"},
  {34, "bass.electric.pick"},
  {35, "bass.electric.fretless"},
  {36, "bass.electric.slap"},
  {37, "bass.electric.slap.pop"},
  {38, "bass.synth"},
  {39, "bass.synth.resonant"},
  {40, "string.bowed.violin"},
  {41, "string.bowed.viola"},
  {42, "string.bowed.cello"},
  {43, "string.bowed.contrabass"},
  {44, "string.bowed.ensemble.tremolo"},
  {45, "string.bowed.ensemble.pizzicato"},
  {46, "string.plucked.harp"},
  {47, "percussion.pitched.drum.timpani"},
  {48, "string.bowed.ensemble"},
  {49, "string.bowed.ensemble.slow"},
  {50, "string.synth"},
  {51, "string.synth.slow"},
  {52, "voice.choir.ah"},
  {53, "voice.choir.ooh"},
  {54, "voice.synth"},
  {55, "sfx.orchestraHit"},
  {56, "brass.trumpet"},
  {57, "brass.trombone"},
  {58, "brass.tuba"},
  {59, "brass.trumpet.muted"},
  {60, "brass.horn"},
  {61, "brass.section"},
  {62, "brass.synth"},
  {63, "brass.synth.soft"},
  {64, "reed.single.sax.soprano"},
  {65, "reed.single.sax.alto"},
  {66, "reed.single.sax.tenor"},
  {67, "reed.single.sax.baritone"},
  {68, "reed.double.oboe"},
  {69, "reed.double.corAnglais"},
  {70, "reed.double.bassoon"},
  {71, "reed.single.clarinet"},
  {72, "flute.piccolo"},
  {73, "flute.concert"},
  {74, "flute.recorder"},
  {75, "flute.pan"},
  {76, "flute.blownBottle"},
  {77, "flute.shakuhachi"},
  {78, "flute.whistle"},
  {79, "flute.ocarina"},
  {80, "lead.square"},
  {81, "lead.saw"},
  {82, "lead.calliope"},
  {83, "lead.chiff"},
  {84, "lead.charang"},
  {85, "lead.voice"},
  {86, "lead.fifths"},
  {87, "lead.bassLead"},
  {88, "pad.newAge"},
  {89, "pad.warm"},
  {90, "pad.poly"},
  {91, "pad.choir"},
  {92, "pad.bowed"},
  {93, "pad.metallic"},
  {94, "pad.halo"},
  {95, "pad.sweep"},
  {96, "texture.rain"},
  {97, "texture.soundtrack"},
  {98, "texture.crystal"},
  {99, "texture.atmosphere"},
  {100, "texture.brightness"},
  {101, "texture.goblins"},
  {102, "texture.echoes"},
  {103, "texture.sciFi"},
  {104, "string.plucked.sitar"},
  {105, "string.plucked.banjo"},
  {106, "string.plucked.shamisen"},
  {107, "string.plucked.koto"},
  {108, "percussion.pitched.metal.kalimba"},
  {109, "reed.double.bagpipe"},
  {110, "string.bowed.violin.fiddle"},
  {111, "reed.double.shehnai"},
  {112, "percussion.pitched.metal.tinkleBell"},
  {113, "percussion.pitched.metal.agogo"},
  {114, "percussion.pitched.metal.steelDrum"},
  {115, "percussion.unpitched.wood.woodblock"},
  {116, "percussion.unpitched.drum.taiko"},
  {117, "percussion.pitched.drum.tom"},
  {118, "percussion.synth.drum"},
  {119, "percussion.unpitched.metal.cymbal.reverse"},
  {120, "sfx.fretNoise"},
  {121, "sfx.breath"},
  {122, "sfx.seashore"},
  {123, "sfx.bird"},
  {124, "sfx.telephone"},
  {125, "sfx.helicopter"},
  {126, "sfx.applause"},
  {127, "sfx.gunshot"},
};

// Generated from docs/instrument-paths.md's "Defaults for general requests" table.
static constexpr GmDefaultEntry kGmPathDefaults[] = {
  {"piano", "piano.acoustic.grand"},
  {"piano.acoustic", "piano.acoustic.grand"},
  {"piano.electric", "piano.electric.tine"},
  {"keyboard", "keyboard.plucked.harpsichord"},
  {"organ", "organ.tonewheel"},
  {"guitar", "guitar.acoustic.steel"},
  {"guitar.electric", "guitar.electric.clean"},
  {"bass", "bass.electric.finger"},
  {"string", "string.bowed.ensemble"},
  {"string.bowed", "string.bowed.violin"},
  {"string.plucked", "string.plucked.harp"},
  {"brass", "brass.trumpet"},
  {"reed", "reed.single.clarinet"},
  {"reed.single.sax", "reed.single.sax.alto"},
  {"flute", "flute.concert"},
  {"voice", "voice.choir.ah"},
  {"lead", "lead.saw"},
  {"pad", "pad.warm"},
  {"texture", "texture.atmosphere"},
  {"percussion", "percussion.pitched.metal.vibraphone"},
  {"kit", "kit.standard"},
};

#endif
