#ifndef _IMPORTEDPADSYNTHTABLE_H_
#define _IMPORTEDPADSYNTHTABLE_H_

#include "OscillatorShapingChain.h"
#include "PadSynthPartialProfile.h"
#include "../dsp/SpectralEnvelopeRemap.h"

#include <cstdint>
#include <unordered_map>
#include <vector>

// PADsynth rendering (docs/padsynth.md) for a preset whose spectrum is
// generated by running a real instrument's own oscillator shape (base
// waveform, harmonic expansion, waveshaper, harmonic filter, time warps,
// spectrum adjustment, harmonic shift - OscillatorShapingChain.h) through
// PADsynth's own partial profile/placement algorithm
// (PadSynthPartialProfile.h) - see docs/padsynth.md's own algorithm
// description.
//
// The sample set is the preset's own real base note/octave span/samples-
// per-octave/table-length layout (docs/padsynth.md's "Sample set"), not a
// fixed C0-anchored octave scheme. getTable(f0) picks the nearest of the
// preset's own M sample points by log-frequency distance.
struct PadSynthParams {
  OscillatorShaping::OscillatorChainParams oscillator;
  PadSynthProfile::ProfileParams profile;
  PadSynthProfile::PositionParams position;

  float bandwidth_cents = 10.0f;

  // Sample set (docs/padsynth.md).
  float base_frequency_hz = 261.6f; // f_b
  int octaves = 6;                  // O
  int samples_per_octave = 2;       // q
  int table_length = 1 << 17;       // L

  int edo_steps = 31;
  bool tuning_matched = true;

  // Anchored spectral-envelope remap + postprocess (dsp/
  // SpectralEnvelopeRemap.h) - step 9 of the chain, shared with
  // SinusoidBank (the <additive> oscillator's own equivalent stage).
  float envelope_anchor_hz = 0.0f;
  float envelope_tracking = 0.0f;
  SpectralPostprocessKind postprocess_kind = SpectralPostprocessKind::None;
  int postprocess_n = 0;
  int postprocess_r = 0;
  float postprocess_amount = 0.0f;

  uint64_t seed = 1;
};

class PadSynthTable {
 public:
  PadSynthTable(int sample_rate, PadSynthParams params);

  // Returns the table covering f0's own region (the nearest sample
  // point), building and caching it on first use.
  const std::vector<float> & getTable(float f0) const;

  // The region's own reference frequency (Hz) that getTable(f0)'s table
  // was actually generated at - see PadSynthVoice.h's own render() for
  // how a voice resamples from this to its note's real pitch.
  float tableBaseFrequency(float f0) const;

  int getSampleRate() const { return sample_rate_; }

 private:
  int sampleCount() const { return params_.octaves * params_.samples_per_octave; }
  float sampleFrequency(int j) const;
  int nearestSampleIndex(float f0) const;
  std::vector<float> renderSample(int j) const;

  int sample_rate_;
  PadSynthParams params_;

  // The oscillator chain's own A[h] (steps 1-8) is frequency-independent -
  // computed once, lazily, and shared by every sample's own step 9/
  // PADsynth placement (which alone vary per sample's own base frequency).
  mutable std::vector<float> oscillator_magnitudes_;
  mutable bool oscillator_magnitudes_built_ = false;
  const std::vector<float> & oscillatorMagnitudes() const;

  mutable std::unordered_map<int, std::vector<float>> tables_;
};

#endif
