#ifndef _LAUNCHPADLAYOUT_H_
#define _LAUNCHPADLAYOUT_H_

#include "Tuning.h"

#include <vector>

// Isomorphic-keyboard grid layout derived from a song's EDO (equal division
// of the octave) and tonic, generalizing the Wicki-Hayden layout (12edo) to
// arbitrary EDOs generated by a good approximate fifth. Pure computation,
// no device/MIDI dependency.
namespace LaunchpadLayout {

  // Steps per octave for a given tuning, or 0 if the tuning has no fixed
  // pitch structure (PERCUSSION) - callers should treat 0 as "no
  // isomorphic layout available for this tuning".
  int edoSteps(Tuning tuning);

  struct Basis {
    int fifth = 0;        // F: best approximation of a 3/2 fifth in N steps
    int whole_tone = 0;    // T: 2F - N
    int semitone = 0;      // S: 3N - 5F
    bool degenerate = true; // true if T<=0 || S<=0 || T==S - callers should
                             // use the chromatic fallback instead of x*T + y*S
  };

  // Computes the (T, S) basis for an N-step EDO.
  Basis computeBasis(int edo_steps);

  // Maps a pad at grid position (x, y), 0-indexed from the bottom-left, to a
  // note value, given the basis and the note at pad (0, 0). Automatically
  // falls back to a straight chromatic run (base + x + y*8) instead of
  // x*T + y*S when basis.degenerate is true.
  int noteForPad(const Basis & basis, int x, int y, int base_note);

  // The major/diatonic scale's pitch classes (mod edo_steps): the chain of
  // fifths from one below the tonic through five above it (F-C-G-D-A-E-B
  // for 12edo), octave-reduced - generalizes the 12edo white/black-key
  // split to any EDO with a non-degenerate basis. Empty if basis.degenerate.
  std::vector<int> diatonicScaleDegrees(const Basis & basis, int edo_steps);

  // Fokker organ / Archiphone style landmark classes, generalized to any
  // EDO: TONIC and the other 6 DIATONIC degrees are the fixed scale
  // skeleton; SHARP/FLAT are a full chromatic step (distance 2) above/
  // below their nearest diatonic degree; DIESIS is a quarter-tone-ish
  // in-between note (distance 1, or >2 in very fine EDOs); ACCIDENTAL is
  // a genuine tie - equidistant from two degrees (e.g. every 12edo black
  // key), ambiguously sharp-or-flat.
  enum class PadCategory { TONIC, DIATONIC, SHARP, FLAT, DIESIS, ACCIDENTAL };

  // Classifies a pad for LED-coloring purposes, by the signed distance
  // from its pitch class to the nearest diatonicScaleDegrees() member.
  // Callers should check basis.degenerate themselves first and use a
  // dedicated fallback color instead of calling this (there's no
  // meaningful scale/tonic distinction once the layout has fallen back to
  // a straight chromatic run).
  PadCategory classifyPad(const Basis & basis, int edo_steps, int x, int y, int base_note);

  // Fixed General MIDI percussion layout (GM values 27-82, the range this
  // engine actually supports - see Note.h's percussion_names table),
  // family-grouped for playability: core kit at the bottom (row 0),
  // ascending through toms/cymbals/hand-percussion/latin/electronic-FX.
  // Returns -1 for the 8 unused pads (row 7, y=7).
  int percussionNoteForPad(int x, int y);

  enum class PercussionFamily { CORE, HI_HAT, TOMS, CYMBALS, HAND_PERC, LATIN, WHISTLE, ELECTRONIC, UNUSED };

  // Classifies a percussion pad for LED-coloring purposes - a separate
  // concern from percussionNoteForPad's placement (hi-hats get their own
  // color regardless of which row they physically sit in).
  PercussionFamily percussionFamilyForPad(int x, int y);

  // Clamps a per-device Launchpad octave shift by delta (+1/-1) to [0, 9] -
  // pure arithmetic shared by LaunchpadManager's octave-up/octave-down.
  int clampOctave(int octave, int delta);

  // Advances a per-device track assignment by delta (+1/-1), clamped to
  // [0, num_tracks). current_or_unassigned == -1 means "not yet assigned
  // to a specific track" (the device has been following some external
  // fallback track so far) - the first advance seeds from that fallback
  // (the caller folds the fallback into current_or_unassigned before
  // calling) rather than starting from 0. Clamps, does not wrap.
  int advanceTrackIndex(int current_or_unassigned, int delta, int num_tracks);

}

#endif
