#ifndef _LAUNCHPADLAYOUT_H_
#define _LAUNCHPADLAYOUT_H_

#include "Tuning.h"

#include <vector>

// Isomorphic-keyboard grid layout derived from a song's EDO (equal division
// of the octave) and tonic, generalizing the Wicki-Hayden layout (12edo) to
// arbitrary EDOs generated by a good approximate fifth. Pure computation,
// no device/MIDI dependency.
namespace LaunchpadLayout {

  // Steps per octave for a given tuning, or 0 if the tuning has no fixed
  // pitch structure (PERCUSSION, LIGHTING) - callers should treat 0 as "no
  // isomorphic layout available for this tuning".
  int edoSteps(Tuning tuning);

  struct Basis {
    int fifth = 0;        // F: best approximation of a 3/2 fifth in N steps
    int whole_tone = 0;    // T: 2F - N
    int semitone = 0;      // S: 3N - 5F
    bool degenerate = true; // true if T<=0 || S<=0 || T==S - callers should
                             // use the chromatic fallback instead of x*T + y*S
  };

  // Computes the (T, S) basis for an N-step EDO.
  Basis computeBasis(int edo_steps);

  // Maps a pad at grid position (x, y), 0-indexed from the bottom-left, to a
  // note value, given the basis and the note at pad (0, 0). Automatically
  // falls back to a straight chromatic run (base + x + y*8) instead of
  // x*T + y*S when basis.degenerate is true.
  int noteForPad(const Basis & basis, int x, int y, int base_note);

  // The major/diatonic scale's pitch classes (mod edo_steps): the chain of
  // fifths from one below the tonic through five above it (F-C-G-D-A-E-B
  // for 12edo), octave-reduced - generalizes the 12edo white/black-key
  // split to any EDO with a non-degenerate basis. Empty if basis.degenerate.
  std::vector<int> diatonicScaleDegrees(const Basis & basis, int edo_steps);

  enum class PadCategory { TONIC, IN_SCALE, CHROMATIC };

  // Classifies a pad for LED-coloring purposes. Callers should check
  // basis.degenerate themselves first and use a dedicated fallback color
  // instead of calling this (there's no meaningful scale/tonic distinction
  // once the layout has fallen back to a straight chromatic run).
  PadCategory classifyPad(const Basis & basis, int edo_steps, int x, int y, int base_note);

}

#endif
