#ifndef _LAUNCHPADLAYOUT_H_
#define _LAUNCHPADLAYOUT_H_

#include "../instruments/Tuning.h"

#include <vector>

// Isomorphic-keyboard grid layout derived from a song's EDO (equal division
// of the octave) and tonic, generalizing the Wicki-Hayden layout (12edo) to
// arbitrary EDOs generated by a good approximate fifth. Pure computation,
// no device/MIDI dependency.
namespace LaunchpadLayout {

  // Steps per octave for a given tuning, or 0 if the tuning has no fixed
  // pitch structure (PERCUSSION) - callers should treat 0 as "no
  // isomorphic layout available for this tuning".
  int edoSteps(Tuning tuning);

  struct Basis {
    int fifth = 0;        // F: best approximation of a 3/2 fifth in N steps
    int whole_tone = 0;    // T: 2F - N
    int semitone = 0;      // S: 3N - 5F
    int major_third = 0;   // M3: best approximation of a 5/4 major third
    int minor_third = 0;   // m3: best approximation of a 6/5 minor third -
                            // M3+m3 == fifth exactly for every EDO this
                            // engine supports (12/19/31/53), which is what
                            // lets computeConsonanceLevels() reuse the
                            // M3:fifth proportion as a single, self-similar
                            // splitting rule at every recursion depth (see
                            // its own doc comment).
    bool degenerate = true; // true if T<=0 || S<=0 || T==S - callers should
                             // use the chromatic fallback instead of x*T + y*S
  };

  // Computes the (T, S) basis for an N-step EDO, plus the major/minor third
  // sizes used by computeConsonanceLevels().
  Basis computeBasis(int edo_steps);

  // Maps a pad at grid position (x, y), 0-indexed from the bottom-left, to a
  // note value, given the basis and the note at pad (0, 0). Automatically
  // falls back to a straight chromatic run (base + x + y*8) instead of
  // x*T + y*S when basis.degenerate is true.
  int noteForPad(const Basis & basis, int x, int y, int base_note);

  // Which of the fixed top-level colors a pad gets (TONIC/FOURTH/FIFTH),
  // or RECURSIVE for everything found by the consonance-splitting
  // recursion below depth 2 - see computeConsonanceLevels().
  enum class PadTier { TONIC, FOURTH, FIFTH, RECURSIVE };

  // A pad's position in the consonance hierarchy: which tier it belongs
  // to, its hue (degrees, meaningful for every tier - TONIC/FOURTH/FIFTH
  // get fixed hues, RECURSIVE pads get the hue computed by the splitting
  // recursion), and its depth (1=TONIC, 2=FOURTH/FIFTH, 3+=RECURSIVE - how
  // many consonance-splits deep this pitch class was first reached).
  struct PadClassification {
    PadTier tier = PadTier::RECURSIVE;
    float hue = 0.0f;
    int depth = 0;
  };

  // Computes every pitch class's consonance classification for an N-step
  // EDO, by recursively splitting the octave the way classical interval
  // theory does: 2/1 = 4/3 * 3/2 (the octave's simplest factor pair is the
  // fourth and fifth), 3/2 = 6/5 * 5/4 (the fifth's simplest factor pair is
  // the minor and major third) - the same operation, just parametrized by
  // successive generators (fifths, then thirds) from the classical
  // consonance sequence. Past thirds there's no further hand-named "next"
  // generator, so every span from depth 3 down reuses the fifth-splits-
  // into-thirds proportion (major_third:fifth), rescaled to that span's
  // own length, as a practical stand-in for "this span's own simplest
  // factor pair" - confirmed to reduce back to the exact major/minor third
  // sizes for any span the length of a fifth, and to reach 100% pitch-class
  // coverage (no leftover/uncategorized notes) for every EDO this engine
  // supports. Each split also assigns a hue, offset from its parent span's
  // hue by a shrinking amount at each depth, so a pitch class's hue stays
  // close to its harmonic neighborhood instead of jumping around.
  // Indexed by pitch class (size edo_steps). Callers should check
  // basis.degenerate themselves first and use a dedicated fallback color
  // instead (there's no meaningful consonance structure once the layout
  // has fallen back to a straight chromatic run).
  std::vector<PadClassification> computeConsonanceLevels(const Basis & basis, int edo_steps);

  // Looks up a pad's consonance classification: resolves its pitch class
  // via noteForPad() the same way the layout itself does, then indexes
  // into a table already computed by computeConsonanceLevels() (computing
  // that table is the expensive part - this lookup is not, so callers
  // refreshing every pad on a grid should call computeConsonanceLevels()
  // once and reuse it here, not recompute it per pad).
  PadClassification classifyPad(const std::vector<PadClassification> & levels, const Basis & basis, int edo_steps, int x, int y, int base_note);

  // Fixed General MIDI percussion layout (GM values 27-82, the range this
  // engine actually supports - see Note.h's percussion_names table).
  // Every named family occupies a contiguous rectangle and never wraps
  // across a row boundary (kit on the left half - x=0..3, hand/latin
  // percussion on the right - x=4..7), unlike the earlier row-linear
  // table this replaced. Returns -1 for the 8 pads that remain
  // unassigned (scattered as small gaps between families, not confined
  // to one row - see PERCUSSION_TABLE's own comment).
  int percussionNoteForPad(int x, int y);

  enum class PercussionFamily { CORE, HI_HAT, TOMS, CYMBALS, KIT_ACCESSORIES, LATIN_DRUMS, LATIN_METAL, SHAKERS, WOODS, CUICA_WHISTLE, ELECTRONIC, UNUSED };

  // Classifies a percussion pad for LED-coloring purposes - a separate
  // concern from percussionNoteForPad's placement (hi-hats get their own
  // color regardless of which row they physically sit in).
  PercussionFamily percussionFamilyForPad(int x, int y);

  // Clamps a per-device Launchpad octave shift by delta (+1/-1) to [0, 9] -
  // pure arithmetic shared by LaunchpadManager's octave-up/octave-down.
  int clampOctave(int octave, int delta);

  // Advances a per-device track assignment by delta (+1/-1), clamped to
  // [0, num_tracks). current_or_unassigned == -1 means "not yet assigned
  // to a specific track" (the device has been following some external
  // fallback track so far) - the first advance seeds from that fallback
  // (the caller folds the fallback into current_or_unassigned before
  // calling) rather than starting from 0. Clamps, does not wrap.
  int advanceTrackIndex(int current_or_unassigned, int delta, int num_tracks);

}

#endif
