#ifndef _LAUNCHPADLAYOUT_H_
#define _LAUNCHPADLAYOUT_H_

#include "../instruments/Tuning.h"

#include <array>
#include <vector>

// Isomorphic-keyboard grid layout derived from a song's EDO (equal division
// of the octave) and tonic, generalizing the Wicki-Hayden layout (12edo) to
// arbitrary EDOs generated by a good approximate fifth. Pure computation,
// no device/MIDI dependency.
namespace LaunchpadLayout {

  // The Tempo/Swing views' number on the 8x8 grid. Three 3x5-pixel digits
  // don't fit eight columns, so the tens digit is the one drawn in full, in
  // white (MIDDLE), centered; the hundreds digit sits to its left and the
  // units digit to its right in the view's colour (SIDE), clipped by the
  // grid edge. No padding: 120 is a SIDE 1, a MIDDLE 2 and a SIDE 0; 50 is a
  // MIDDLE 5 and a SIDE 0; 9 has no tens digit, so nothing is MIDDLE and
  // only the SIDE 9 shows. Rows are top-first: cells[row][column]. Values
  // are clamped to 0-999.
  enum class NumberPixel { OFF, SIDE, MIDDLE };
  using NumberGrid = std::array<std::array<NumberPixel, 8>, 8>;
  NumberGrid renderNumber(int value);

  // Steps per octave for a given tuning, or 0 if the tuning has no fixed
  // pitch structure (PERCUSSION) - callers should treat 0 as "no
  // isomorphic layout available for this tuning".
  int edoSteps(Tuning tuning);

  struct Basis {
    int fifth = 0;        // F: best approximation of a 3/2 fifth in N steps
    int whole_tone = 0;    // T: 2F - N
    int semitone = 0;      // S: 3N - 5F
    int major_third = 0;   // M3: best approximation of a 5/4 major third
    int minor_third = 0;   // m3: best approximation of a 6/5 minor third -
                            // M3+m3 == fifth exactly for every EDO this
                            // engine supports (12/19/31/53), which is what
                            // lets computeConsonanceLevels() reuse the
                            // M3:fifth proportion as a single, self-similar
                            // splitting rule at every recursion depth (see
                            // its own doc comment).
    bool degenerate = true; // true if T<=0 || S<=0 || T==S - callers should
                             // use the chromatic fallback instead of x*T + y*S
  };

  // Computes the (T, S) basis for an N-step EDO, plus the major/minor third
  // sizes used by computeConsonanceLevels().
  Basis computeBasis(int edo_steps);

  // Maps a pad at grid position (x, y), 0-indexed from the bottom-left, to a
  // note value, given the basis and the note at pad (0, 0). Automatically
  // falls back to a straight chromatic run (base + x + y*8) instead of
  // x*T + y*S when basis.degenerate is true.
  int noteForPad(const Basis & basis, int x, int y, int base_note);

  // Which of the fixed top-level colors a pad gets (TONIC/FOURTH/FIFTH),
  // or RECURSIVE for everything found by the consonance-splitting
  // recursion below depth 2 - see computeConsonanceLevels().
  enum class PadTier { TONIC, FOURTH, FIFTH, RECURSIVE };

  // A pad's position in the consonance hierarchy: which tier it belongs
  // to, its hue (degrees, meaningful for every tier - TONIC/FOURTH/FIFTH
  // get fixed hues, RECURSIVE pads get the hue computed by the splitting
  // recursion), its depth (1=TONIC, 2=FOURTH/FIFTH, 3+=RECURSIVE - how
  // many consonance-splits deep this pitch class was first reached), and
  // two enharmonic fields, both 0 unless computeConsonanceLevels()'s
  // overlay pass found a genuine collision here (always the case for
  // TONIC/FOURTH/FIFTH - family doesn't apply to them): enharmonic_blend,
  // how much this pitch class should read as neither family (0 = cleanly
  // major/minor, 1 = maximally ambiguous), and enharmonic_depth, the
  // shallowest mediant-recursion depth any colliding ratio pair was found
  // at (see collectMediantCollisions()) - a low value (e.g. a third's own
  // immediate split, the shallowest that actually occurs) marks a
  // structurally fundamental collision, distinct from a pitch class only
  // implicated via many/deeper ratio pileups.
  struct PadClassification {
    PadTier tier = PadTier::RECURSIVE;
    float hue = 0.0f;
    int depth = 0;
    float enharmonic_blend = 0.0f;
    int enharmonic_depth = 0;
  };

  // Computes every pitch class's consonance classification for an N-step
  // EDO, by recursively splitting the octave the way classical interval
  // theory does: 2/1 = 4/3 * 3/2 (the octave's simplest factor pair is the
  // fourth and fifth), 3/2 = 6/5 * 5/4 (the fifth's simplest factor pair is
  // the minor and major third) - the same operation, just parametrized by
  // successive generators (fifths, then thirds) from the classical
  // consonance sequence. Past thirds there's no further hand-named "next"
  // generator, so every span from depth 3 down reuses the fifth-splits-
  // into-thirds proportion (major_third:fifth), rescaled to that span's
  // own length, as a practical stand-in for "this span's own simplest
  // factor pair" - confirmed to reduce back to the exact major/minor third
  // sizes for any span the length of a fifth, and to reach 100% pitch-class
  // coverage (no leftover/uncategorized notes) for every EDO this engine
  // supports. Each split also assigns a hue, offset from its parent span's
  // hue by a shrinking amount at each depth, so a pitch class's hue stays
  // close to its harmonic neighborhood instead of jumping around.
  // Indexed by pitch class (size edo_steps). Callers should check
  // basis.degenerate themselves first and use a dedicated fallback color
  // instead (there's no meaningful consonance structure once the layout
  // has fallen back to a straight chromatic run).
  //
  // After the recursion above settles every pitch class' tier/hue/depth,
  // a final overlay pass looks for genuine enharmonic collisions and
  // fills in enharmonic_blend - the tuning can't actually keep two
  // distinct, independently-real JI ratios apart at that pitch class, so
  // coloring the pad as belonging to just one family (major or minor)
  // would be a false precision the EDO doesn't have. This isn't a fixed,
  // hand-picked list of ratio pairs to check (a coarser EDO needs fewer,
  // a finer one keeps finding more the deeper you look - 12-EDO's whole
  // tone collision, 9/8 vs 10/9, generalizes one level further into
  // 31-EDO's minor-third split, 12/11 vs 11/10, both landing on
  // "C-double-sharp") - it's the same mediant-splitting construction the
  // recursion above already uses once, at depth 3 (fifth = minor_third *
  // major_third), applied again to whatever it just produced, as deep as
  // each EDO's own step resolution can still tell two results apart (see
  // the implementation for the exact termination rule). A pitch class
  // often collides more than once, at various depths - every hit adds to
  // its score (deeper/more complex ratio pairs count for less per hit,
  // but a pitch class near unison typically collects many of them, from
  // every branch of the mediant tree eventually shrinking there), and
  // enharmonic_blend is that total normalized against the EDO's own
  // single worst pitch class, so it reads as "how bad is this, relative
  // to the worst this tuning actually has" rather than a fixed cross-EDO
  // scale. This is also why every pitch class gets a real family color
  // and none are ever flattened to an achromatic "too deep to tell" gray
  // the way RECURSIVE depth used to be capped: enharmonic_blend carries
  // that information continuously instead of a hard depth cutoff
  // throwing it away. TONIC/FOURTH/FIFTH pitch classes are left alone
  // (family doesn't apply to them).
  std::vector<PadClassification> computeConsonanceLevels(const Basis & basis, int edo_steps);

  // Looks up a pad's consonance classification: resolves its pitch class
  // via noteForPad() the same way the layout itself does, then indexes
  // into a table already computed by computeConsonanceLevels() (computing
  // that table is the expensive part - this lookup is not, so callers
  // refreshing every pad on a grid should call computeConsonanceLevels()
  // once and reuse it here, not recompute it per pad).
  PadClassification classifyPad(const std::vector<PadClassification> & levels, const Basis & basis, int edo_steps, int x, int y, int base_note);

  // Fixed General MIDI percussion layout (GM values 27-82, the range this
  // engine actually supports - see Note.h's percussion_names table).
  // Every named family occupies a contiguous rectangle and never wraps
  // across a row boundary (kit on the left half - x=0..3, hand/latin
  // percussion on the right - x=4..7), unlike the earlier row-linear
  // table this replaced. Returns -1 for the 8 pads that remain
  // unassigned (scattered as small gaps between families, not confined
  // to one row - see PERCUSSION_TABLE's own comment).
  int percussionNoteForPad(int x, int y);

  enum class PercussionFamily { CORE, HI_HAT, TOMS, CYMBALS, KIT_ACCESSORIES, LATIN_DRUMS, LATIN_METAL, SHAKERS, WOODS, CUICA_WHISTLE, ELECTRONIC, UNUSED };

  // The 4x4 drum rack in the bottom-left corner (x, y in 0..3, row 0 at the
  // bottom): kick, snare and hats on the bottom row, then side stick, clap,
  // pedal hat and crash, the four lower toms, and the upper toms, ride and
  // cowbell. -1 for every pad outside the block.
  int drumPadNoteForPad(int x, int y);

  // The family of a GM percussion note, for LED coloring (UNUSED if it has
  // none).
  PercussionFamily percussionFamilyForNote(int note);

  // The scale keyboard: pad (x, y) is scale degree x + kScaleRowStride * y
  // above the tonic, so each row up is a fourth (three degrees of a
  // seven-note scale).
  constexpr int kScaleRowStride = 3;
  int scaleDegreeIndexForPad(int x, int y);

  // The split view while a clip is open: rows 0-3 stay the playing surface,
  // rows 4-7 are 32 steps, left to right then bottom to top.
  constexpr int kPlayRows = 4;
  constexpr int kStepsPerView = 32;
  // The step a pad in the step rows stands for, or -1 outside them.
  int stepForPad(int x, int y);

  // Classifies a percussion pad for LED-coloring purposes - a separate
  // concern from percussionNoteForPad's placement (hi-hats get their own
  // color regardless of which row they physically sit in).
  PercussionFamily percussionFamilyForPad(int x, int y);

  // Clamps an absolute octave shifted by delta (+1/-1) to
  // [constants::MIN_OCTAVE, constants::MAX_OCTAVE] - pure arithmetic used
  // both for Controller's own global octave (Controller::octaveUp()/
  // octaveDown()) and, combined with a per-device offset, for
  // LaunchpadManager::octave()'s resolved per-device octave.
  int clampOctave(int octave, int delta);

  // Clamps a per-device octave *offset* (relative to whatever the global
  // octave currently is, not an absolute octave itself) shifted by delta
  // (+1/-1) to [-(MAX_OCTAVE-MIN_OCTAVE), MAX_OCTAVE-MIN_OCTAVE] - shared
  // by LaunchpadManager's own octave-up/octave-down (the physical hardware
  // buttons) and its per-model connect-time default nudge
  // (defaultOctaveOffsetForModel()).
  int clampOctaveOffset(int offset, int delta);

  // Advances a per-device track assignment by delta (+1/-1), clamped to
  // [0, num_tracks). current_or_unassigned == -1 means "not yet assigned
  // to a specific track" (the device has been following some external
  // fallback track so far) - the first advance seeds from that fallback
  // (the caller folds the fallback into current_or_unassigned before
  // calling) rather than starting from 0. Clamps, does not wrap.
  int advanceTrackIndex(int current_or_unassigned, int delta, int num_tracks);

  // The Pan pads: a horizontal fader per track row, 8 pads with the centre
  // between columns 3 and 4, 22.5 degrees per pad out to +-90 at the outer
  // pads (negative azimuth is left). Shown as a bar growing from the centre
  // toward that side; a value behind the listener (|azimuth| > 90) lights
  // the whole row, and exactly 0 dimly marks the two inner pads. Stateless,
  // so the LED display and the pad-press handler use the same convention.
  constexpr float kPanPadDegrees = 22.5f;
  constexpr float kPanRearDegrees = 180.0f;
  enum class PanPad { OFF, CENTER, BAR, TIP };
  // How each of a row's 8 pads shows `azimuth`: the bar's length rounds
  // away from zero, so any nonzero azimuth shows at least one pad on its
  // own side and is never mistaken for centred.
  std::array<PanPad, 8> panBarPads(float azimuth);
  // The azimuth a single press on `column` sets.
  float panPadToAzimuth(int column);

}

#endif
