
#ifndef _CONTROLLER_H_
#define _CONTROLLER_H_

#include "audio/AudioBuffer.h"
#include "instruments/InstrumentProvider.h"
#include "playback/EventQueue.h"
#include "state/PlaybackInfo.h"
#include "ambisonic/ChannelConfiguration.h"
#include "ambisonic/MixerType.h"

#include <functional>
#include <memory>
#include <mutex>
#include <set>
#include <string>
#include <utility>
#include <vector>

class Song;

class Controller {
 public:
  Controller(ChannelConfiguration _channel_config);

  const Song & getSong() const { return *current_song; }
  Song & getSong() { return *current_song; }

  // Player::play() (the audio thread) needs this instead of getSong()
  // above: createNewSong()/openSong() reassign current_song on the UI
  // thread, and getSong() only ever hands out a reference into whatever
  // Song current_song happened to point to at the moment of the call -
  // a plain `Song &` from *before* a reassignment is a dangling reference
  // the instant the old Song's refcount (current_song was its only owner)
  // drops to 0, which a UI-thread reassignment can do synchronously,
  // regardless of when the audio thread later notices the swap via
  // SONG_CHANGED. Returning an actual shared_ptr copy - under the same
  // mutex createNewSong()/openSong() take to reassign
  // current_song, see song_mutex_'s own comment - keeps the *old* Song
  // object alive for as long as the audio thread's own copy of the
  // pointer is still in use, however long after the UI thread has moved
  // on to a new one.
  std::shared_ptr<Song> getSongPtr() const {
    std::lock_guard<std::mutex> guard(song_mutex_);
    return current_song;
  }

  const std::string & getSongFilename() const { return current_song_filename; }

  void createNewSong();
  bool openSong(const std::string & filename);

  bool sendCommand(std::string_view s);

  // Lets the UI layer (which Controller, part of the headless-testable
  // synth_engine lib, must not depend on) supply a fallback for command
  // names sendCommand() doesn't recognize itself - e.g. per-widget Emacs
  // commands like "set-mark" that live in a UIElement's CommandRegistry.
  void setCommandFallback(std::function<bool(std::string_view)> fn) { command_fallback_ = std::move(fn); }

  std::shared_ptr<AudioBuffer> startRecording() {
    current_sample = std::make_shared<AudioBuffer>(1, 0);
    return current_sample;
  }

  void stopRecording() { current_sample.reset(); }
  bool isRecording() const { return current_sample.get() != nullptr; }
  int getRecordingTrackId() const { return recording_track_id; }
  void setRecordingTrackId(int track_id) { recording_track_id = track_id; }
  const AudioBuffer & getCurrentSample() const { return current_sample ? *current_sample : empty_sample; }
  void addToSample(const AudioBuffer & other) {
    if (current_sample) current_sample->append(other);
  }

  EventQueue & getUIEventQueue() { return ui_event_queue; }
  EventQueue & getPlaybackEventQueue() { return playback_event_queue; }

  // Audio thread -> VisualizationThread only (see VisualizationThread.h) -
  // carries raw AudioBlockEvents, never anything UI-facing; results come
  // back the other way via ui_event_queue (VisualizationResultEvent).
  EventQueue & getVisualizationQueue() { return visualization_queue; }

  // Plain overwrite - used by togglePlaying()/moveEditPosition()/
  // setEditPosition() for their own optimistic local updates (which must
  // always win immediately, no reconciliation needed) as well as anywhere
  // else that just wants to seed the mirror directly.
  void setPlaybackInfo(const PlaybackInfo & info) { playback_info = info; }
  const PlaybackInfo & getPlaybackInfo() const { return playback_info; }

  // The one path a real Player-thread snapshot (PlaybackEvent, forwarded
  // by UI::handlePlaybackEvent()) should come in through, instead of
  // setPlaybackInfo() directly. A snapshot generated by the audio thread's
  // own per-block render (state_.renderBlock() runs on every audio callback
  // regardless of play state) before it drained a just-pushed
  // MOVE_POSITION/SET_POSITION control event is stale for the edit-position
  // fields specifically (absolute/pattern/row) - applying it would clobber
  // a more recent local prediction moveEditPosition()/setEditPosition()
  // already made, then get silently corrected again once a caught-up
  // snapshot arrives: a visible cursor jump-back-then-forward. Detected via
  // PlaybackInfo::getPositionEditSeq() vs. this Controller's own
  // local_position_edit_seq_ (bumped once per moveEditPosition()/
  // setEditPosition() call, mirroring SongState::getPositionEditSeq(),
  // bumped once per processed control event) - everything else in `info`
  // (voice counts, is_playing, meters, ...) is always accepted as-is
  // regardless, same as a plain setPlaybackInfo() would.
  void receivePlaybackSnapshot(const PlaybackInfo & info);

  ChannelConfiguration getChannelConfiguration() const { return channel_config; }

  // Process-wide decoder choice, independent of any particular song (any
  // song can be rendered through any decoder - see MixerType.h). Only
  // meaningful when getChannelConfiguration().getType() == AMBISONIC - a
  // MONO config never attempts binaural decoding regardless of this
  // setting (see MixerFactory.cpp).
  MixerType getMixerType() const { return mixer_type_; }
  void setMixerType(MixerType mixer_type) { mixer_type_ = mixer_type; }

  // AMBISONIC_BINAURAL has two underlying implementations - MagLS
  // (AmbisonicMagLSDecoder, the default) and the older virtual-speaker
  // rig (AmbisonicBinauralMixer) - without a third MixerType value for it
  // (see MixerType.h's own comment on why): this is a separate, orthogonal
  // toggle, same shape as --stereo's own force_cardioid, reachable via
  // --legacy-binaural (main.cpp). Ignored entirely unless mixer_type_ is
  // actually AMBISONIC_BINAURAL (see MixerFactory.cpp).
  bool getUseLegacyBinaural() const { return use_legacy_binaural_; }
  void setUseLegacyBinaural(bool use_legacy) { use_legacy_binaural_ = use_legacy; }

  bool togglePlaying();

  // Row navigation while stopped (PatternEditor's move-row-up/down,
  // Page Up/Down, note-entry/backspace's own step, kill-region's bounds
  // adjustment, LaunchpadManager's step-entry advance/auto-stop landing
  // spot) goes through here rather than pushing MOVE_POSITION/SET_POSITION
  // directly, for the same reason togglePlaying() above updates its own
  // mirror synchronously instead of only pushing an event: the UI thread's
  // own main loop (TerminalUI::readInput()) drains every currently-buffered
  // terminal keystroke in one tight loop before ever returning to poll()
  // and giving the Player thread's PlaybackEvent round-trip a chance to be
  // read back - so a burst of terminal-generated key auto-repeat (holding
  // Backspace, or a note key, on a non-Kitty terminal) can call this
  // several times before getPlaybackInfo() ever reflects the first move,
  // making every press in the burst read-and-act-on the same stale row
  // while the rows in between are silently skipped. Updating the local
  // PlaybackInfo mirror immediately - not waiting on the async round trip -
  // means each press in a burst sees the previous one's result right away,
  // exactly like togglePlaying()'s existing synchronous flip. The
  // corresponding MOVE_POSITION/SET_POSITION event is still pushed, purely
  // to keep the audio thread's own SongState in sync for when playback
  // actually starts.
  void moveEditPosition(int delta_rows);
  void setEditPosition(int absolute_row);

  // Whether a pattern-editor selection (mark) is currently open -
  // PatternEditor mirrors its own selection_active_ here on every change
  // (set-mark, kill-region/kill-ring-save's own clear, keyboard-quit, the
  // auto-clear on playback start/pattern crossing in its render()).
  // moveEditPosition()/setEditPosition() only clamp row navigation to the
  // current pattern (Song::clampRowToCurrentPattern() - keeps a mark from
  // ending up stranded in a different pattern than the cursor) while this
  // is true; with no selection open there's nothing to strand, so
  // navigation crosses pattern boundaries freely, the same way playback's
  // own row-by-row advance (SongState::movePosition()) already does.
  void setPatternSelectionActive(bool active) { pattern_selection_active_ = active; }

  // Single, shared home for "mutate this track's mute/solo/send and keep
  // the already-running playback state in sync" - neither the terminal's
  // `\` key handler nor any Launchpad control (the two ways a user can
  // trigger these today) duplicate this logic; both just resolve which
  // track_id to act on (whichever way is natural for that input source -
  // the shared on-screen cursor, or a Launchpad device's own assigned
  // track) and call these. Returns false (Send setters: no-op) if track_id
  // doesn't name an existing InstrumentTrack/PercussionTrack. Each also
  // pushes the matching PlaybackControlEvent so the change actually reaches
  // the running SongState, not just the Track model - see
  // InstrumentTrackState's public setMuted/setSolo/setSendA/setSendB/
  // setSendMain.
  bool toggleTrackMuted(int track_id);
  bool toggleTrackSolo(int track_id);
  void setTrackSendA(int track_id, float value);
  void setTrackSendB(int track_id, float value);
  void setTrackSendMain(int track_id, float value);
  void setTrackAzimuth(int track_id, float value);

  // Note columns (chord/polyphony width, VisibleTrackInfo::num_subtracks_)
  // are otherwise purely derived from actual note data (see Pattern::
  // getTrackInformation()) - these two adjust InstrumentTrack's own
  // minNoteColumns floor that derivation also takes the max against, a
  // Renoise-style manual override so an empty column can be added ahead of
  // typing into it. No PlaybackControlEvent (unlike the setters above):
  // this only affects display/editing, never audio - the running SongState
  // never reads it.
  void addNoteColumn(int track_id);
  void removeNoteColumn(int track_id);

  // Single, shared home for the whole-row-replace sweep a realtime
  // recording session (auto-record-while-held, both the terminal keyboard
  // path in PatternEditor and the Launchpad pad path in LaunchpadManager)
  // uses to make a fresh take overwrite a row's old content rather than
  // merging into it. Idempotent per (row, track_id) against `cleared_rows`
  // - `insert().second` is false once a pair's already been cleared this
  // session - so every live-input write site can call this defensively
  // without worrying about which one gets there first or double-clearing.
  // `cleared_rows` (and when it resets) stays owned by the caller rather
  // than moving in here too: PatternEditor's and LaunchpadManager's
  // recording sessions are independent and can be active at the same time
  // (different tracks), so sharing one set here would let one session's
  // end (which clears its own bookkeeping) reset the other's mid-session
  // and cause a stray re-clear that wipes notes the other session already
  // wrote this take.
  void ensureRowCleared(std::set<std::pair<int, int>> & cleared_rows, int pattern_idx, int row, int track_id);

  // Sweeps ensureRowCleared() over every row the transport has newly
  // passed through since the last call, for every track named in
  // `track_ids` - the onRowAdvanced() half of the realtime auto-record
  // session, shared by PatternEditor and LaunchpadManager the same way
  // ensureRowCleared() itself is (see its own comment for why the session
  // bookkeeping stays owned by the caller). Resyncs to just `new_row`
  // rather than trying to backfill a range, if the pattern changed or the
  // row went backwards (a loop/pattern-sequence wraparound) - a range
  // spanning that boundary has no single well-defined meaning. `track_ids`
  // stays a caller-computed parameter rather than something this method
  // resolves itself: PatternEditor derives it from active_keyboard_notes_,
  // LaunchpadManager unions it across every device's own active_notes -
  // different data structures per input source, not shareable here.
  void sweepAutoRecordRows(std::set<std::pair<int, int>> & cleared_rows, int & last_cleared_row, int & last_cleared_pattern_idx, int pattern_idx, int new_row, const std::vector<int> & track_ids);

  // Engages the realtime auto-play-while-held session (PatternEditor's
  // keyboard entry and LaunchpadManager's pad entry both offer this):
  // starts the transport and mutes the song's own pattern-driven
  // scheduling (SongState::render()'s own comment has the full reasoning)
  // so only this live take's own PLAY_NOTE/STOP_NOTE/NOTE_PRESSURE stream
  // sounds, then resets the caller's whole-row-replace bookkeeping for the
  // fresh session. The caller decides *when* to call this - its own "is
  // this the first held note, and are we not already playing" check
  // (again per-input-source state, not shareable) - so it's only ever
  // called once per session, right before that session's first write.
  void startAutoRecordSession(bool & auto_started_playback, std::set<std::pair<int, int>> & cleared_rows, int & last_cleared_row, int & last_cleared_pattern_idx);

  // The matching end of startAutoRecordSession(): stops the transport
  // (only if it's still genuinely playing - the user may have manually
  // stopped it mid-hold already, and toggling again here would incorrectly
  // restart it) and lands the cursor just past the final note-off this
  // take wrote, then unmutes the song's own scheduling and clears the
  // session flag/bookkeeping unconditionally either way, so a manual
  // mid-hold stop never leaves recording muted or the flag stuck true.
  // The caller decides when the session is over (its own "last held note
  // just released" check) and passes its current PlaybackInfo snapshot so
  // the landing position is computed from the same snapshot the check
  // itself saw, not a value that may have drifted by the time this runs.
  void stopAutoRecordSession(bool & auto_started_playback, std::set<std::pair<int, int>> & cleared_rows, const PlaybackInfo & info);

  // Writes an explicit note-off at `row` for a live take's release, once
  // the transport has moved past the note's own row - shared tail of
  // PatternEditor::offerInput()'s and LaunchpadManager::handlePadEvent()'s
  // RELEASE handling (mirroring handleMidiEvent()'s own NOTE_OFF write).
  // Per Renoise's own pattern model, a single line can't hold both a note
  // and its own note-off, so the caller only calls this once it's
  // confirmed `row` isn't still the note's own row - writing here
  // unconditionally would erase the note it belongs to instead of ending
  // it. Sweeps the row clean first (like every other live write site) when
  // this caller's own session started the transport.
  void writeReleaseOff(std::set<std::pair<int, int>> & cleared_rows, bool auto_started_playback, int pattern_idx, int row, int track_id, int note_column, int delay);

  // Applies a pressure/aftertouch update to an already-written note -
  // shared by PatternEditor::handleMidiEvent()'s NOTE_PRESSURE handling
  // (physical MIDI keyboard input) and LaunchpadManager::handlePadEvent()'s
  // AFTERTOUCH handling. Leaves the caller to bump the song version or set
  // its own row_edited flag afterward, whichever that input path already
  // uses (the two aren't unified - see the one-row partial redraw's own
  // reasoning elsewhere), and to resolve which row/rate-limiting rules
  // apply before calling this - only the actual read-modify-write of the
  // note itself is shared.
  void applyNotePressure(int pattern_idx, int row, int track_id, int note_column, short velocity, int delay);

  // Emacs prefix-argument style: transient, one-shot context a caller (the
  // Launchpad command-dispatch path, UI::handleLaunchpadButtonEvent) sets
  // right before invoking a named command by string (executeCommand()),
  // for whichever registered command actually wants it (currently
  // "toggle-mute"/"toggle-solo", resolving which track a specific
  // Launchpad device is following - see PatternEditor's constructor) - the
  // caller doesn't need to know which commands care, and a command that
  // doesn't consume it simply leaves it to be overwritten/cleared by the
  // next dispatch. consumePendingCommandTrack() reads and clears in one
  // step, exactly like reading Emacs's current-prefix-arg resets it - so a
  // stale value can never leak into a later, unrelated command (e.g. one
  // invoked from a keybinding or M-x, which never sets this at all and
  // always gets the caller-supplied fallback instead).
  void setPendingCommandTrack(int track_id) { pending_command_track_ = track_id; }
  int consumePendingCommandTrack(int fallback) {
    if (pending_command_track_ < 0) return fallback;
    int track_id = pending_command_track_;
    pending_command_track_ = -1;
    return track_id;
  }

  const InstrumentProvider & getInstrumentProvider() const { return instrument_provider; }

 private:
  ChannelConfiguration channel_config;
  MixerType mixer_type_ = MixerType::AMBISONIC_STEREO;
  bool use_legacy_binaural_ = false;

  std::shared_ptr<Song> current_song;
  // Guards current_song's own reassignment (createNewSong()/openSong())
  // against Player::play()'s getSongPtr() call on the audio
  // thread - see that method's own comment for the use-after-free this
  // prevents. mutable so a const Controller& can still lock it in
  // getSongPtr(). Every other current_song access (getSong() and its many
  // UI-thread callers) needs no lock of its own: they're never concurrent
  // with a reassignment, which is also always on the UI thread.
  mutable std::mutex song_mutex_;
  std::string current_song_filename = "song.xml";
  std::shared_ptr<AudioBuffer> current_sample;
  InstrumentProvider instrument_provider;
  EventQueue ui_event_queue, playback_event_queue, visualization_queue;
  PlaybackInfo playback_info;
  // How many position-editing control events moveEditPosition()/
  // setEditPosition() have themselves pushed - compared against each
  // incoming snapshot's own PlaybackInfo::getPositionEditSeq() by
  // setPlaybackInfo() to detect a stale one. See that method's own
  // comment.
  int local_position_edit_seq_ = 0;
  int recording_track_id = 0;
  std::function<bool(std::string_view)> command_fallback_;
  int pending_command_track_ = -1;
  bool pattern_selection_active_ = false;

  static inline AudioBuffer empty_sample;
};

#endif
